import {
    hyNotification,
    hyMessage,
    hyButton,
    hyIcon,
    hyButtonGroup,
    hyCollapse,
    hyCollapseItem,
    hyAlert,
    hyTooltip,
    hyPopconfirm,
    hyDropdown,
    hyDropdownItem,
    hyConfigProvider,
    hyInput,
    hyMessageBox,
    hyLoading,
} from "@hy-element/components";
import type { Plugin } from 'vue'

export default [
    hyButton,
    hyIcon,
    hyButtonGroup,
    hyCollapse,
    hyCollapseItem,
    hyAlert,
    hyTooltip,
    hyPopconfirm,
    hyDropdown,
    hyDropdownItem,
    hyConfigProvider,
    hyMessage,
    hyNotification,
    hyInput,
    hyMessageBox,
    hyLoading,
] as Plugin[]